2025-04-17 13:00:27,811 - INFO - 
2025-04-17 13:00:27,812 - INFO - Running remote tests...
2025-04-17 13:00:28,049 - INFO - ============================= test session starts ==============================
2025-04-17 13:00:28,049 - INFO - platform linux -- Python 3.12.3, pytest-7.4.4, pluggy-1.4.0
2025-04-17 13:00:28,049 - INFO - rootdir: /home/student/Desktop/uthp-tests/remote
2025-04-17 13:00:28,049 - INFO - configfile: pytest.ini
2025-04-17 13:00:28,049 - INFO - collected 6 items
2025-04-17 13:00:50,141 - INFO - remote/test_grimmj1708_serial.py Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,141 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,142 - INFO - Hex string: 88310d973fffa81101d101ffda
2025-04-17 13:00:50,142 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,142 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,142 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,143 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,143 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,143 - INFO - Hex string: 88c20204357b
2025-04-17 13:00:50,144 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,144 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,144 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Hex string: 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Checksum is valid for 88310d973fffa81101d101ffda
2025-04-17 13:00:50,145 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,145 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88c20204357b
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,146 - INFO - Checksum is valid for 88310d973fffa81001d101ffdb
2025-04-17 13:00:50,147 - INFO - .
2025-04-17 13:00:55,153 - INFO - remote/test_serial.py Serial Output:
2025-04-17 13:00:55,154 - INFO - UTHP-R1-0021 login:
2025-04-17 13:00:55,157 - INFO - .
2025-04-17 13:00:55,804 - INFO - remote/test_ssh.py SSH Output: SSH_SUCCESS
2025-04-17 13:00:55,804 - INFO - [SUCCESS] SSH authentication verified.
2025-04-17 13:00:55,804 - INFO - uthp@UTHP-R1-0021
2025-04-17 13:00:56,271 - INFO - .Root login attempt failed as expected: Authentication failed.
2025-04-17 13:00:56,273 - INFO - .
2025-04-17 13:01:57,178 - INFO - remote/test_truck_devil_serial.py F
2025-04-17 13:02:08,854 - INFO - remote/test_truck_devil_tcp.py Command output:
2025-04-17 13:02:08,856 - INFO - F
2025-04-17 13:02:08,857 - INFO - =================================== FAILURES ===================================
2025-04-17 13:02:08,857 - INFO - ____________________________ test_serial_read_write ____________________________
2025-04-17 13:02:08,857 - INFO -     def test_serial_read_write():
2025-04-17 13:02:08,857 - INFO -         """Ensure that the truckdevil serial read runs without errors."""
2025-04-17 13:02:08,857 - INFO -         command = "python3 ./truckdevil.py add_device m2 can0 500000 " + os.getenv("TRUCKDEVIL_PORT") + " run_module read_messages set num_messages 5 print_messages"
2025-04-17 13:02:08,857 - INFO - >       result = subprocess.run(command, shell=True, capture_output=True, text=True, timeout=60)
2025-04-17 13:02:08,857 - INFO - /home/student/Desktop/uthp-tests/remote/test_truck_devil_serial.py:60:
2025-04-17 13:02:08,857 - INFO - _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2025-04-17 13:02:08,857 - INFO - /usr/lib/python3.12/subprocess.py:550: in run
2025-04-17 13:02:08,857 - INFO -     stdout, stderr = process.communicate(input, timeout=timeout)
2025-04-17 13:02:08,857 - INFO - /usr/lib/python3.12/subprocess.py:1209: in communicate
2025-04-17 13:02:08,857 - INFO -     stdout, stderr = self._communicate(input, endtime, timeout)
2025-04-17 13:02:08,857 - INFO - /usr/lib/python3.12/subprocess.py:2116: in _communicate
2025-04-17 13:02:08,857 - INFO -     self._check_timeout(endtime, orig_timeout, stdout, stderr)
2025-04-17 13:02:08,857 - INFO - _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2025-04-17 13:02:08,857 - INFO - self = <Popen: returncode: -9 args: 'python3 ./truckdevil.py add_device m2 can0 500...>
2025-04-17 13:02:08,857 - INFO - endtime = 46049.875633879, orig_timeout = 60, stdout_seq = [], stderr_seq = []
2025-04-17 13:02:08,857 - INFO - skip_check_and_raise = False
2025-04-17 13:02:08,857 - INFO -     def _check_timeout(self, endtime, orig_timeout, stdout_seq, stderr_seq,
2025-04-17 13:02:08,857 - INFO -                        skip_check_and_raise=False):
2025-04-17 13:02:08,858 - INFO -         """Convenience for checking if a timeout has expired."""
2025-04-17 13:02:08,858 - INFO -         if endtime is None:
2025-04-17 13:02:08,858 - INFO -             return
2025-04-17 13:02:08,858 - INFO -         if skip_check_and_raise or _time() > endtime:
2025-04-17 13:02:08,858 - INFO - >           raise TimeoutExpired(
2025-04-17 13:02:08,858 - INFO -                     self.args, orig_timeout,
2025-04-17 13:02:08,858 - INFO -                     output=b''.join(stdout_seq) if stdout_seq else None,
2025-04-17 13:02:08,858 - INFO -                     stderr=b''.join(stderr_seq) if stderr_seq else None)
2025-04-17 13:02:08,858 - INFO - E           subprocess.TimeoutExpired: Command 'python3 ./truckdevil.py add_device m2 can0 500000 /dev/ttyACM1 run_module read_messages set num_messages 5 print_messages' timed out after 60 seconds
2025-04-17 13:02:08,858 - INFO - /usr/lib/python3.12/subprocess.py:1253: TimeoutExpired
2025-04-17 13:02:08,858 - INFO - ________________________________ test_tcp_read _________________________________
2025-04-17 13:02:08,858 - INFO -     def test_tcp_read():
2025-04-17 13:02:08,858 - INFO -         """Ensure that the truckdevil serial read runs without errors."""
2025-04-17 13:02:08,858 - INFO -         ssh_host = os.getenv("SSH_HOST")
2025-04-17 13:02:08,858 - INFO -         time.sleep(10)  # wait for the service to start
2025-04-17 13:02:08,858 - INFO -         # read messages only because we would have to spin another port up
2025-04-17 13:02:08,858 - INFO -         command = f"python3 ./truckdevil.py add_device m2:{ssh_host} can0 500000 1234 run_module read_messages set num_messages 5 print_messages"
2025-04-17 13:02:08,858 - INFO -         result = subprocess.run(command, shell=True, capture_output=True, text=True)
2025-04-17 13:02:08,858 - INFO -         print("Command output:\n", result.stdout)
2025-04-17 13:02:08,858 - INFO - >       assert result.returncode == 0, f"Command failed with return code {result.returncode}"
2025-04-17 13:02:08,858 - INFO - E       AssertionError: Command failed with return code 1
2025-04-17 13:02:08,858 - INFO - E       assert 1 == 0
2025-04-17 13:02:08,859 - INFO - E        +  where 1 = CompletedProcess(args='python3 ./truckdevil.py add_device m2:192.168.7.2 can0 500000 1234 run_module read_messages set...nit__\n    self._socket.connect((self._tcp_ip, self._port))\nConnectionRefusedError: [Errno 111] Connection refused\n').returncode
2025-04-17 13:02:08,859 - INFO - /home/student/Desktop/uthp-tests/remote/test_truck_devil_tcp.py:61: AssertionError
2025-04-17 13:02:08,859 - INFO - =========================== short test summary info ============================
2025-04-17 13:02:08,859 - INFO - FAILED remote/test_truck_devil_serial.py::test_serial_read_write - subprocess...
2025-04-17 13:02:08,859 - INFO - FAILED remote/test_truck_devil_tcp.py::test_tcp_read - AssertionError: Comman...
2025-04-17 13:02:08,859 - INFO - =================== 2 failed, 4 passed in 100.87s (0:01:40) ====================
2025-04-17 13:02:08,921 - INFO - Process finished with return code 1
2025-04-17 13:02:08,921 - INFO - Environment variables cleaned up.
